### ISSUE TITLE
It crashes on large field groups

### ISSUE THREAD

**Issue by canozangulcihan** [Hube2/acf-custom-field-locations-rule#6]
Hi,

I have a relatively large field group with multiple flexible contents. Seems like it crashes when I try to open this field group.

**Comment by Hube2** [comment]
This plugin/extension is more of an experiment and I doubt it will work well on a site with a lot of large field groups. To be honest, I don't use this because the global setting of location rules for all choice fields is overkill and creates extremely slow admin performance. You should check the code used in this plugin, it is not that complex, and create your own custom code to target only the one or two fields that you want to use to conditionally show other field groups. The admin performance would be much better.

**Comment by Hube2** [comment]
See #4 and #3
